### PR TITLE
Use dwdav in webdav.js

### PR DESCRIPTION
**Pull request by tnguyen14**
This address #5 

I took a look and seems like most of the code in webdav.js is very similar to dwdav. So I figure it would make sense to just consume that package.

In the original `webdav.js`, each method has an optional root. However, after searching through the source code, I don't see that option being used anywhere. If you think that is an important feature, I would be more than happy to include that in dwdav.

The one thing I didn't implement in dwdav is the hack to speed up things by calling a get request in unzip. I am not sure what that does. But it sounds like maybe it's something dwdav could implement as well?

/cc @SqrTT

### CODE REVIEW

**Comment by tnguyen14** [comment]
I just realized that you do use the optional root. I've added that as part of `dwdav` in v2.2.0.

Also, I'd suggest that in the `uploadCartridges` function, instead of calling `post` and `unzip` separately, `postAndUnzip` should be used.

**Comment by SqrTT** [comment]
Hi @tnguyen14,
Yes, basically this is your version but slightly extended. Because before was no npm version of `dwdav`.   I hope that this is not a problem that I borrowed your solution, right?

Currently I can't marge this PR because there is little issue with `extending` class. In `dwdav` you are exporting anonymous function that create instance of DWDAV but anonymous function can't be extended after... So please consider this PR https://bitbucket.org/demandware/dwdav/pull-requests/2/export-dwdav-constructor-to-be-able-extend/diff

> The one thing I didn't implement in dwdav is the hack to speed up things by calling a get request in unzip. I am not sure what that does

That hack is designed to solve strange atom behavior, by some reason it don't want to send request until second is not proceed, so that's why there is that temporary solution. :(

> Also, I'd suggest that in the uploadCartridges function, instead of calling

Yes, that's what it was before. But now between them is called  `notify` function which is designed to notify UI about current uploading status.

Thanks, for your consideration of package.

**Comment by tnguyen14** [comment]
Sorry for the late response. I've merged for PR on dwdav and published a new version for it (`v2.3.0`).

If you want me to put the hack for get request in, let me know.

**Comment by SqrTT** [comment]
unfortunately, there is no easy way to replace this package.

**Pull request closed without merging**
